collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4419979
color:
  saturation: 0.2744361
  brandStrength: 0.04154758
  rhythmicContrast: 0.5642151
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  lightness: 0.5314032
layout_spectrum: 1
name: Daniel Marsh
